config/routes.rb
Portfolio::Application.routes.draw do
 
  resources :users 

  get "post", to: "posts#show", as: :post

 
  resources :posts do

    post 'comments', to: "posts#create_comment", as: :comments
  end

  root to: "static_pages#home"

  get "home", to: "static_pages#home", as: :home
  get "about", to: "static_pages#about", as: :about
  get "project", to: "static_pages#project", as: :project
 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :author, :message 

  validates :author, presence: true
  validates :message, length: { maximum: 800}, presence: true
  validates :post, presence: true 
   before_validation :set_author_to_anonymous_if_blank
  # private

   #def set_author_to_anonymous_if_blank
    # if self.author.blank?
     #  self.author = ' Anonymous'
   #end

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  scope :featured, -> { where(featured: true) }
  scope  :ordered, -> {order( 'published_at DESC') }
  default_scope -> {where("published_at <= ? ", Time.now) .order ("published_at DESC")}
  attr_accessible :author, :body, :featured, :published_at, :title
  validates :title, :body, presence: true

  validates :title, 
            length: { in: 6..65 }, 
            presence: true, 
            uniqueness: true
  #validate :published_at_is_in_the_future, on: :create

#private

 #  def validates_published_at_is_in_the_future
 #     errors.add(:published_at, "Published at must be in the future") unless published_at >= Time.now
 # end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # def create_comment
  #   @post = Post.find(params[:posts_id])
  #   @comment = @post.comments.new(params[:comment])
  #   respond_to do |format|
  #     if @comment.save
  #       format.html { redirect_to @post, notice: 'Comment was successfully added.' }
  #       format.json { render json: @post, status: :created, location: @post }
  #     else
  #       format.html { render action: "show" }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def create_comment
    @post = Post.find(params[:id])
    @comments = @post.comments.new(params[:comment])
    respond_to do |format|
      if @comments.save
        format.html { redirect_to @post, notice: 'Comment was successfully added.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "show" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
   @post = Post.featured
   @post = Post.featured.first
  end

  end

  def about
    
  end

  def project

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    
    <%= link_to "Home", home_path %>
    <%= link_to "About Me", about_path %>
    <a href= '/posts'>Blog</a>
    <%= link_to "Projects", project_path %>

  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>


<h1>   </h1>

<body>
    <section id= "content">
    <%= render "layouts/navigation" %>
    <%= yield %>
    <section>
</body>


<footer>
    <p> &copy; <%= Time.now.year %> Rebecca Nguyen </p>
</footer>

</html>

app/views/posts/_comment.html.erb
<%= form_for(@comment, url: post_comments_path(@post)) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %> 
   </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div> 
 <!--  <%#= @post.published_at.strftime(("Published on %m/%d/%Y")) %> -->
 <!--  <div class="field">
    <%#= f.label :author %><br />
    <%#= f.text_field :author %>
  </div>
  <div class="field">
    <%#= f.label :featured %><br />
    <%#= f.text_field :featured %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<%= link_to 'Comment' post_comments_path %>

app/views/posts/index.html.erb
<h1>Rebecca's Blog</h1>

<% @posts.each do |post| %>
    <div>
      <h3><%= post.title %></h3>
      <p><%= post.body %></p>
      <p><%= post.published_at.strftime(("Published on %m/%d/%Y at %I:%M%P")) %>
      </p>
    
    <%= link_to 'Comment', post_comments_path %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>

<% end %>


<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>Add New Post</h1>

<%= render 'posts/form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
  <%= render 'posts/comment' %>
  
<p>
  <!-- <b>Title:</b> -->
  <b><%= @post.title %></b>
</p>

  <!-- <b>Body:</b> -->
 <p> <%= @post.body %></p>

<p>
 <!--  <b>Published:</b>  -->
  <%= @post.published_at.strftime(("Published on %m/%d/%Y")) %>
</p> 

<p>
  <!-- <b>Author:</b> -->
  <%#= @post.author %>
</p>
<!-- <p>
  <b>Featured:</b>
  <%= @post.featured %>
</p> -->

  <h3> Comments (<%= @post.comments.count %>) </h3>

  <% @post.comments.each do |comment| %>
    <% unless comment.id.nil? %>
      <%= comment.author %>
      <small> <%= comment.created_at.strftime(("Commented on %m/%d/%Y")) %> </small>
      <%= simple_format(comment.message) %>
    <% end %>
  <% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path(@post)%>
<%= link_to 'Show', posts_path(@post) %>

app/views/static_pages/about.html.erb
<h1>About Rebecca</h1>

<p>Rebecca Nguyen currently resides in Park City, UT...</p>

app/views/static_pages/home.html.erb
<h1>Rebecca Nguyen</h1>

<p> The personal web site of Rebecca Nguyen.</p>

app/views/static_pages/project.html.erb
<h1>Projects</h1>

<p>This page contains the links of Rebecca's web projects.</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>First name</th>
    <th>Last name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>